/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        card: {
          DEFAULT: "var(--color-card)",
          foreground: "var(--color-card-foreground)",
        },
        popover: {
          DEFAULT: "var(--color-popover)",
          foreground: "var(--color-popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-primary-foreground)",
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          foreground: "var(--color-secondary-foreground)",
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
        },
        muted: {
          DEFAULT: "var(--color-muted)",
          foreground: "var(--color-muted-foreground)",
          lighter: "var(--color-muted-lighter)",
          darker: "var(--color-muted-darker)",
        },
        accent: {
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-accent-foreground)",
          50: "var(--color-accent-50)",
          100: "var(--color-accent-100)",
          200: "var(--color-accent-200)",
          300: "var(--color-accent-300)",
          400: "var(--color-accent-400)",
          500: "var(--color-accent-500)",
          600: "var(--color-accent-600)",
          700: "var(--color-accent-700)",
          800: "var(--color-accent-800)",
          900: "var(--color-accent-900)",
        },
        complementary: {
          DEFAULT: "var(--color-complementary)",
          foreground: "var(--color-complementary-foreground)",
          50: "var(--color-complementary-50)",
          100: "var(--color-complementary-100)",
          200: "var(--color-complementary-200)",
          300: "var(--color-complementary-300)",
          400: "var(--color-complementary-400)",
          500: "var(--color-complementary-500)",
          600: "var(--color-complementary-600)",
          700: "var(--color-complementary-700)",
          800: "var(--color-complementary-800)",
          900: "var(--color-complementary-900)",
        },
        destructive: {
          DEFAULT: "var(--color-destructive)",
          foreground: "var(--color-destructive-foreground)",
          50: "var(--color-destructive-50)",
          100: "var(--color-destructive-100)",
          200: "var(--color-destructive-200)",
          300: "var(--color-destructive-300)",
          400: "var(--color-destructive-400)",
          500: "var(--color-destructive-500)",
          600: "var(--color-destructive-600)",
          700: "var(--color-destructive-700)",
          800: "var(--color-destructive-800)",
          900: "var(--color-destructive-900)",
        },
        success: {
          DEFAULT: "var(--color-success)",
          foreground: "var(--color-success-foreground)",
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          foreground: "var(--color-warning-foreground)",
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
        },
        info: {
          DEFAULT: "var(--color-info)",
          foreground: "var(--color-info-foreground)",
          50: "var(--color-info-50)",
          100: "var(--color-info-100)",
          200: "var(--color-info-200)",
          300: "var(--color-info-300)",
          400: "var(--color-info-400)",
          500: "var(--color-info-500)",
          600: "var(--color-info-600)",
          700: "var(--color-info-700)",
          800: "var(--color-info-800)",
          900: "var(--color-info-900)",
        },
        neon: {
          DEFAULT: "var(--color-neon)",
          primary: "var(--color-neon-primary)",
          secondary: "var(--color-neon-secondary)",
          accent: "var(--color-neon-accent)",
          complementary: "var(--color-neon-complementary)",
        },
        neonGlow: {
          primary: "var(--color-neon-glow-primary)",
          secondary: "var(--color-neon-glow-secondary)",
          accent: "var(--color-neon-glow-accent)",
          complementary: "var(--color-neon-glow-complementary)",
        },
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-md)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow-md)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
      },
      typography: {
        DEFAULT: {
          css: {
            color: "var(--color-foreground)",
            lineHeight: "1.7",
            maxWidth: "none",

            h1: {
              color: "var(--color-primary-400)",
              fontWeight: "700",
              fontSize: "1.875rem",
              marginTop: "2rem",
              marginBottom: "1.5rem",
            },
            h2: {
              color: "var(--color-accent-400)",
              fontWeight: "700",
              fontSize: "1.5rem",
              marginTop: "1.5rem",
              marginBottom: "1rem",
            },
            h3: {
              color: "var(--color-secondary-400)",
              fontWeight: "600",
              fontSize: "1.25rem",
              marginTop: "1.5rem",
              marginBottom: "0.75rem",
            },
            h4: {
              color: "var(--color-foreground)",
              fontWeight: "600",
              fontSize: "1.125rem",
              marginTop: "1.25rem",
              marginBottom: "0.5rem",
            },
            p: {
              color: "var(--color-muted-foreground-lighter)",
              marginBottom: "0.25rem",
              lineHeight: "1.5",
            },
            a: {
              color: "var(--color-primary)",
              textDecoration: "underline",
              textDecorationThickness: "1px",
              textUnderlineOffset: "2px",
              "&:hover": {
                color: "var(--color-primary-300)",
              },
            },
            ul: {
              listStyleType: "disc",
              paddingLeft: "1.5em",
              marginTop: "0.5rem",
              marginBottom: "0.5rem",
              lineHeight: "1.25",
              "& > li": {
                marginTop: "0",
                marginBottom: "0",
              },
            },
            ol: {
              listStyleType: "decimal",
              paddingLeft: "1.5em",
              marginTop: "0.5rem",
              marginBottom: "0.5rem",
              lineHeight: "1.25",
              "& > li": {
                marginTop: "0",
                marginBottom: "0",
              },
            },
            li: {
              marginTop: "0",
              marginBottom: "0",
              paddingLeft: "0.25rem",
              lineHeight: "1.25",
              color: "var(--color-muted-foreground-lighter)",
            },
            "li::marker": {
              color: "var(--color-primary-400)",
            },
            strong: {
              color: "var(--color-foreground)",
              fontWeight: "600",
            },
            blockquote: {
              fontWeight: "500",
              fontStyle: "italic",
              color: "var(--color-muted-foreground)",
              borderLeftWidth: "3px",
              borderLeftColor: "var(--color-accent)",
              paddingLeft: "1em",
              marginTop: "1.5rem",
              marginBottom: "1.5rem",
            },
            code: {
              color: "var(--color-secondary-300)",
              fontWeight: "400",
              backgroundColor: "var(--color-muted)",
              padding: "0.2rem 0.4rem",
              borderRadius: "0.25rem",
              fontFamily: "var(--font-mono)",
            },
            "code::before": {
              content: '""',
            },
            "code::after": {
              content: '""',
            },
            pre: {
              color: "var(--color-foreground)",
              backgroundColor: "var(--color-muted)",
              padding: "0.5rem",
              borderRadius: "0.375rem",
              overflow: "auto",
              fontFamily: "var(--font-mono)",
              marginTop: "1rem",
              marginBottom: "1.5rem",
            },
            "pre code": {
              backgroundColor: "transparent",
              borderWidth: "0",
              borderRadius: "0",
              padding: "0",
              fontWeight: "400",
              color: "inherit",
            },
            hr: {
              borderColor: "var(--color-muted-lighter)",
              marginTop: "2rem",
              marginBottom: "2rem",
            },
            img: {
              borderRadius: "0.5rem",
              marginTop: "1.5rem",
              marginBottom: "1.5rem",
            },
          },
        },
        lg: {
          css: {
            fontSize: "1.125rem",
          },
        },
        invert: {
          css: {
            "--tw-prose-body": "var(--color-muted-foreground-lighter)",
            "--tw-prose-headings": "var(--color-foreground)",
            "--tw-prose-links": "var(--color-primary)",
            "--tw-prose-code": "var(--color-secondary-300)",
            "--tw-prose-pre-code": "var(--color-foreground)",
            "--tw-prose-pre-bg": "var(--color-muted)",
            "--tw-prose-hr": "var(--color-muted-lighter)",
          },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
