name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:  # Allows manual triggering

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      # Copy the example custom-seeds file to satisfy TypeScript during CI
      - name: Create custom-seeds.ts from example for typecheck
        run: cp src/lib/db/seeds/custom-seeds.example.ts src/lib/db/seeds/custom-seeds.ts
      - run: pnpm typecheck

  build:
    name: Build
    needs: [lint, typecheck]
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      # Copy the example custom-seeds file to satisfy TypeScript during CI build
      - name: Create custom-seeds.ts from example for build
        run: cp src/lib/db/seeds/custom-seeds.example.ts src/lib/db/seeds/custom-seeds.ts
      - run: pnpm build
